[package]
name = "poems"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bip39 = "2.0.0"
colored = "2.0.4"
hex = "0.4.3"
rand = "0.8.5"
wasm-bindgen = "0.2.87"

[lib]
crate-type = ["cdylib"]


